# Generated by Django 2.1.5 on 2019-02-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190211_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_followed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='following',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user_1', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user_1', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followings', through='accounts.Following', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='followed',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user_2', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='followed',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user_2', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.ManyToManyField(related_name='followeds', through='accounts.Followed', to='accounts.Profile'),
        ),
    ]
