# Generated by Django 2.1.5 on 2019-02-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190212_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='followed',
            name='following_user',
        ),
        migrations.RemoveField(
            model_name='following',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='following',
            name='following_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followed',
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='_profile_following_+', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='Followed',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
