# Generated by Django 2.1.5 on 2019-02-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='playlists.Comments', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='scrap',
            field=models.ManyToManyField(related_name='scrap', through='playlists.Scrap', to='accounts.Profile'),
        ),
    ]
