# Generated by Django 2.1.5 on 2019-02-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190211_0640'),
        ('playlists', '0002_auto_20190211_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='scrap',
        ),
        migrations.AddField(
            model_name='scrap',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scrap_user', to='accounts.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_playlist', to='playlists.PlayList'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='consists_of',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consists_of_place', to='playlists.Place'),
        ),
        migrations.AlterField(
            model_name='consists_of',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consists_of_playlist', to='playlists.PlayList'),
        ),
        migrations.AlterField(
            model_name='place',
            name='consists_of',
            field=models.ManyToManyField(related_name='consists_of', through='playlists.Consists_of', to='playlists.PlayList'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_playlist', to='playlists.PlayList'),
        ),
    ]
