# Generated by Django 2.1.5 on 2019-02-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20190217_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='star',
            field=models.FloatField(),
        ),
    ]
