# Generated by Django 2.1.5 on 2019-02-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190216_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scrap_playlist',
            new_name='scrap_playlists',
        ),
    ]
