# Generated by Django 2.1.5 on 2019-02-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_created_at'),
        ('accounts', '0004_auto_20190216_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_tags',
            field=models.ManyToManyField(to='playlists.Tag'),
        ),
    ]
