# Generated by Django 2.1.5 on 2019-02-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190211_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/images/default_profile.png', upload_to='accounts/media'),
        ),
    ]
