# Generated by Django 2.1.5 on 2019-02-11 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20190211_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consists_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('place_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('main_image', models.ImageField(upload_to='playlist/main_image/%Y/%m/%d')),
                ('tag', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('comments', models.ManyToManyField(related_name='_playlist_comments_+', through='playlists.Comments', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='playlists.PlayList')),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='scrap',
            field=models.ManyToManyField(related_name='_playlist_scrap_+', through='playlists.Scrap', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='place',
            name='consists_of',
            field=models.ManyToManyField(related_name='_place_consists_of_+', through='playlists.Consists_of', to='playlists.PlayList'),
        ),
        migrations.AddField(
            model_name='consists_of',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='playlists.Place'),
        ),
        migrations.AddField(
            model_name='consists_of',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='playlists.PlayList'),
        ),
        migrations.AddField(
            model_name='comments',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='playlists.PlayList'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='card',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.Place'),
        ),
    ]
