# Generated by Django 2.1.5 on 2019-02-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_auto_20190214_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagged',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='tagged',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tagged',
        ),
    ]
