# Generated by Django 2.1.5 on 2019-02-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_auto_20190217_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stars',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='stars',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='stars',
        ),
        migrations.DeleteModel(
            name='Stars',
        ),
    ]
