# Generated by Django 2.1.5 on 2019-02-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_auto_20190217_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cost',
            field=models.IntegerField(default=10000000),
            preserve_default=False,
        ),
    ]
