# Generated by Django 2.1.5 on 2019-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0009_auto_20190220_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='place',
        ),
        migrations.AddField(
            model_name='card',
            name='location',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
